kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.ClusterRole.name }}
  namespace: {{ .Values.Common.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.ServiceAccount.name }}
    namespace: {{ .Values.Common.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.Role.name }}
  apiGroup: rbac.authorization.k8s.io
