apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ConfigMap.name }}
  namespace: {{ .Values.Common.Namespace }}
  labels:
    app: {{ .Values.Common.ServiceName }}
data:
  application.yaml: |-
    spring:
      jpa:
        show-sql: true
        open-in-view: true
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        hibernate:
          naming:
            implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          use-new-id-generator-mappings: false
        properties:
          hibernate:
            hbm2ddl:
              auto: create-drop # create / update / validate / create-drop / none # 초기 메타테이블 Migration완료 후 필드 주석처리
            format_sql: true
            dialect: org.hibernate.dialect.MariaDB103Dialect # Target Database Dialect Setting 필요
      # dataflow Database EndPoint
      datasource:
        driverClassName: com.mysql.cj.jdbc.Driver #
        url: >-
          jdbc:mysql://${BATCHADMIN_DB_HOST}/dataflow?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
          &serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        username: ${BATCHADMIN_DATABASE_USERNAME}
        password: ${BATCHADMIN_DATABASE_PASSWORD}
        hikari:
          maximumPoolSize: 5
          maxLifetime: 55000
          poolName: batch-main-pool
          dataSourceProperties:
            cachePrepStmts: true
            prepStmtCacheSize: 50
            prepStmtCacheSqlLimit: 2048
      # 메타테이블 Migration용 설정, 반영완료 후 주석처리
      flyway:
        enabled: true
        baselineVersion: 4
        baselineOnMigrate: true
        table: flyway_schema_history_dataflow
        locations:
          - classpath:org/springframework/cloud/dataflow/server/db/migration/{vendor}